sudo: required
services:
- docker
before_install:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- chmod ugo+x ./build.sh
script:
- docker-compose build verifyclient
- docker-compose run --rm verifyclient sh -c "yarn && yarn test"
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ];  then echo "production"; elif ["$TRAVIS_BRANCH"
  == "develop"]; then echo "stage"; else echo "dev-$(git rev-parse --short HEAD)"
  ; fi`
- "./build.sh $TAG"
env:
  global:
  - secure: Gtd2pE1KvyPg0aOMpRDzlcHxl4oBJ1TR7bUXOjIuoQY6pLe6MPN2XkyrF2Efqhcfyr7BQ9t9P41kXSdYaLsaq7UIFzXXtYRtAs1Wb2H7qDyckaJCFL1DtpxoVtqeB6cWm9DjhF1w72bZ5NzBT7a1zdEkPw6g7ZffaOw0StDxXpBumCYBHcAZTXrv3Vn+Ab4slBwxhBY3S+NkpmNmmPmK2nlrmDsIVE6Zs7ihJ5W7cOMX9nLuHklqZjf8wgAhvUfwijxLJznCue5dqLEhptQqSmqKdDOOEBfXK9jRCM77wlVFcQGb6JqNGtZc8wtKGYrWd3f5M6GCHOvXCGFHMp43jb9B76/J4xIWm1zA9dnmgQRFGtNUxyLwv4trTduu0s2+aeZFfNal67m8K6O0J+FQmAgF33xO7b5FTuxHajmwHNopQuLrVN+QlJanUUOvFpzMSuPNBZoNSu/BXju3TYvNgiobQ7Nu8AM9Med11RXVDSSVPkfKSu8SJreXq8d9f6yGhSbmftgm19t0WHa5CBQrBnpS5Q72mdvwhV44yYMMfQGnh4S4p4Ih2H50MG1WqFfJX2JIp4YfMnnU2aCVgQhhgGJwgnbLiF+U66I8tbRod+Ql4+HoqqNYbtUpJ8VRaDd6LFcgDkBTEXF/CoCnhLf02sHomuGFxAjXmGphAnCJiT4=
notifications:
  slack:
    secure: XkpxurHZJxQuhwnAnQvhWEIIOJGLywHQgW+DLjNCxwo4nM82IbsTY4a6JicsO0jkzdkxX1yk5W4pB7BbBeiuwLC72gRZGmD2AY1EZThsPsVtv6aMi6VXgYyiAgAv2gV8Dv7P8MsHnSiqkwuIwHnveu3QA2yTjnsDeyfsMWRSdH1C4kb6EpsxMV2LE0KxEtM88Vney2Qm82LhSyB0x9c2ExVsQOOtseKMaeA2KXgm0b2wJLmYgtapk8eZszC9fao4ANkCfVvipt78C4eJvska/0KGem36k7ZKZm+Qgk8SUWU1YHALOznsCzuVKErwuaurDxgFcImxQgGdQ2+ygHQPqdh16i0kmEu/TPb1IxKSf8a2NBUfoSutneDmrJAD9peEFnXvAA2D8RICtLMkxprXgPgncEwRlPdfpMI/F7xv/+1u2xWjUrSME2IjHFUACLbdnrKH6VSnCrXZmKTLC0+nsujAEPELqSWfJ3xzNReKf6XqCADVSm4rwvbaV9E4YlFNiPKnQTpV3ELe0hEcouI4kKAYWR59g6QLjYacVvosK2Gv0q8c9jo67X1Tf3E4gOiN7Ai3qjKSwlE3QXaQzlHPEzzje0ImdT39F2dCTdydTgh6PX23B6IIfHwZE1PGn8oHwtpZ/kZ9K739W7TwAkbW6Bv94uXrGTOlQGn0iMBZIAY=
