sudo: required
services:
- docker
before_install:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- chmod ugo+x ./build.sh
script:
- docker-compose build verifyclient
- docker-compose run --rm verifyclient sh -c "yarn && yarn test"
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ];  then echo "production"; elif ["$TRAVIS_BRANCH"
  == "develop"]; then echo "stage"; else echo "dev-$(git rev-parse --short HEAD)"
  ; fi`
- "./build.sh $TAG"
env:
  global:
  - secure: Gtd2pE1KvyPg0aOMpRDzlcHxl4oBJ1TR7bUXOjIuoQY6pLe6MPN2XkyrF2Efqhcfyr7BQ9t9P41kXSdYaLsaq7UIFzXXtYRtAs1Wb2H7qDyckaJCFL1DtpxoVtqeB6cWm9DjhF1w72bZ5NzBT7a1zdEkPw6g7ZffaOw0StDxXpBumCYBHcAZTXrv3Vn+Ab4slBwxhBY3S+NkpmNmmPmK2nlrmDsIVE6Zs7ihJ5W7cOMX9nLuHklqZjf8wgAhvUfwijxLJznCue5dqLEhptQqSmqKdDOOEBfXK9jRCM77wlVFcQGb6JqNGtZc8wtKGYrWd3f5M6GCHOvXCGFHMp43jb9B76/J4xIWm1zA9dnmgQRFGtNUxyLwv4trTduu0s2+aeZFfNal67m8K6O0J+FQmAgF33xO7b5FTuxHajmwHNopQuLrVN+QlJanUUOvFpzMSuPNBZoNSu/BXju3TYvNgiobQ7Nu8AM9Med11RXVDSSVPkfKSu8SJreXq8d9f6yGhSbmftgm19t0WHa5CBQrBnpS5Q72mdvwhV44yYMMfQGnh4S4p4Ih2H50MG1WqFfJX2JIp4YfMnnU2aCVgQhhgGJwgnbLiF+U66I8tbRod+Ql4+HoqqNYbtUpJ8VRaDd6LFcgDkBTEXF/CoCnhLf02sHomuGFxAjXmGphAnCJiT4=
  - secure: SjToN2OOwavtn2lH+Znj3x1vw7Xb9XkZ8EKXF+Cd6sz5UIB2/ESS4kveTvSNbpSuNBPSQLXkPevDYUoRnVMzJWjDkyZbuIUJwpU/ReX49ysXFGq9jmUFZvbuSXHtgHGX9s0Xb+2i8JSH9c2pihmvbXAiturIcusJKONBrgvgVbJ6gkKsKw05JMAPoIOG+HyEOaFNAp4mUaTUgIssUuWtGqxyeln75HlbkkwJ2NA8fzw6h2Nb7437LBF3hHt+9SD8iyNQWKx9E/8dDXYXV+zQrRL/kK33jsaQiF1u07WwVWG3SH2xi2Xwvl7oyUV07fQ6ImahAJKUxI9+E7CzAQ1C888iMripywCZuWw/VfJ3+igQH/MZdcKVfM6E6mV6Uosv+mkA8TwkVV2Ll/tAdeoZECQuxu7J6lOP1utRQgZ9PhnVWzKOwIDYYJQTaj9HTxSS1WAMvbe51xTFSupkbarOoxF0HMb+zIt5OeJqh/prZUo61XkZBRWoxlpNsUE8Vyk/w2cno76URvbPx9Mii+Z8xxkS5kpH+Tea6tDzCopvJWM3jY1qT9bpO21zLDW4OJVHx7dPocRsZBuNPt/E6E6M1guoG5aVbqhyZfsPbaZbd7lEvEJy5gjWcOrz/3majXKB78EIKRrThxQ2nYpHFRdgSxV9GKIQSySSyUw74T37jl8=
notifications:
  slack:
    secure: XkpxurHZJxQuhwnAnQvhWEIIOJGLywHQgW+DLjNCxwo4nM82IbsTY4a6JicsO0jkzdkxX1yk5W4pB7BbBeiuwLC72gRZGmD2AY1EZThsPsVtv6aMi6VXgYyiAgAv2gV8Dv7P8MsHnSiqkwuIwHnveu3QA2yTjnsDeyfsMWRSdH1C4kb6EpsxMV2LE0KxEtM88Vney2Qm82LhSyB0x9c2ExVsQOOtseKMaeA2KXgm0b2wJLmYgtapk8eZszC9fao4ANkCfVvipt78C4eJvska/0KGem36k7ZKZm+Qgk8SUWU1YHALOznsCzuVKErwuaurDxgFcImxQgGdQ2+ygHQPqdh16i0kmEu/TPb1IxKSf8a2NBUfoSutneDmrJAD9peEFnXvAA2D8RICtLMkxprXgPgncEwRlPdfpMI/F7xv/+1u2xWjUrSME2IjHFUACLbdnrKH6VSnCrXZmKTLC0+nsujAEPELqSWfJ3xzNReKf6XqCADVSm4rwvbaV9E4YlFNiPKnQTpV3ELe0hEcouI4kKAYWR59g6QLjYacVvosK2Gv0q8c9jo67X1Tf3E4gOiN7Ai3qjKSwlE3QXaQzlHPEzzje0ImdT39F2dCTdydTgh6PX23B6IIfHwZE1PGn8oHwtpZ/kZ9K739W7TwAkbW6Bv94uXrGTOlQGn0iMBZIAY=
deploy:
  provider: npm
  email: aleksand-isaev@yandex.ru
  api_key:
    secure: aS/5hImt7uXTM1qoi0Vl4ji/UsFF3J9D6Es9vXa8aQPuF38jbgD5cWed0sfg9cD+/QxLGct9AOf1ZyrQlbENCSLU3apg5wi8od3nfBQJ9GMwkSSBy0b7ERVOy+Oq0+goVwptFr9tRHH9aeM+Z2fbjFBzfbGouYMw/FltS6lRzvxX4NGYlYBSjeuBORJBy3WU58sNlvB0pc7LQy496OYFivEROVkS+lS6r5YUJEESJRZCiuMA0cq4E5QMY70DC4XrMUo164RSOaYiT0RxSxVm1zBlOqk1HDmjwZtghFhDHzkG19tihM//vZHrLb1Xz5CRHhAl2M+MCWIumbZ82J4K++cHU3KCKGtI4AyFDgGTcwkPeQ8BA2zwdI/BzbwMK7XTbbGJUwa7mEdHIls+pJkRHzZBuwR375pGtTkpwjcen4bxTuVohIFAjukRrvjuXzalQS7KRnnFwIn8LL8RxHSPoiwMPI3IL6QOmgfqlBOZbfa+udE7v0n4eR0JzDN4pHpEzjHdl9V+FEAtUkye0IznFWMLQr5BYNaw9lezker99lBomwlZWwNZfixHJyA26bJmJvDOiksmNRCgfPbU3klo1U8pFVF//U5Z1ztkBMRcaSlUl8mmgM1G6X0WQ813jC2VM0HLeeOWC2qRwDH+ZBrRbOHjTdSOZ8w6p2CCbayRqq8=
  on:
    tags: true
    repo: JincorTech/verify-ts-client
